server:
  port: 8765
spring:
  application:
    name: consumer-dubbo

dubbo:
  application:
    name: consumer-dubbo
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://192.168.220.125:8848
  config-center:
    address: nacos://192.168.220.125:8848
  metadata-report:
    address: nacos://192.168.220.125:8848

